spring:
  #数据库链接
  datasource:
    dynamic:
      primary: system #设置默认的数据源或者数据源组,默认值即为system
      strict: false
      datasource:
        system:
          url: jdbc:mysql://1.12.248.138:3306/system_server?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 46176qwert
        table_schema:
          url: jdbc:mysql://1.12.248.138:3306/information_schema?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 46176qwert
  servlet:
    multipart:
      max-file-size: 99999MB
      max-request-size: 99999MB
  redis:
    host: 1.12.248.138
    port: 6379
    password: 123456
    database: 0

server:
  #端口号
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml # 自定义xml文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #在映射实体类时候,将数据库表名和字段中下划线去掉,按照驼峰命名


